spring.application.name=tiny-url-app
server.port=8000
h2.console.enabled=true
h2.console.path=/h2-console
#jdbc:h2:file:/data/tinyurldb
#jdbc:h2:mem:tinyurldb
spring.datasource.url=jdbc:h2:file:/data/tinyurldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


#redis-12810.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:12810

# Redis connection properties
spring.cache.type=redis
spring.redis.host=redis-12810.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port=12810
spring.redis.password=1rubwknBEJiCybGRyYF83pt41EeWro16
#spring.cache.redis.time-to-live=60000


logging.level.io.lettuce=DEBUG
logging.level.org.springframework.data.redis=DEBUG



# Redis connection properties
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.cache.redis.time-to-live=60000

app.url.prefix=http://localhost:8000/api/s/
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


logging.level.org.springframework=INFO
logging.level.com.example.tinyurl=DEBUG

#server.error.include-message=always
#server.error.include-binding-errors=always
#
#spring.main.banner-mode=off
#spring.jackson.serialization.indent_output=true
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#
#



management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.metrics.export.simple.enabled=true
management.server.port=8010

